### PR TITLE
Fix charset in GUI for macOS

### LINKED ISSUE #63: Bug: Impossible to open files with non ASCII characters in their names
Hi,

On Win 10x64, opening a file with a UTF-8 accent like

> Gravats débris pierre.wav

produced this error:

> 2019-06-18 17:17:39 E:\Bureau\Gravats dÃ©bris pierre.wav: File does not exist

I think file has to be escaped somewhere.

Meanwhile, I'll avoid any non-ASCII characters.

Thanks for your support !

### PR DESCRIPTION
**Pull request by g-maxime**
Fixes #63 

Signed-off-by: Maxime Gervais <gervais.maxime@gmail.com>

### CODE REVIEW

File: Source/GUI/Qt/App.cpp [hunk 1]
```diff
@@ -43,6 +43,11 @@ int main (int argc, char** argv)
     Core C;
     C.Errors_Continue=true; //Always for the GUI
 
+    // QApplication initialisation reset charset to default (ASCII when launched from finder) value.
+    #ifdef __MACOSX__
+    setlocale(LC_CTYPE, "UTF-8");
```
Comment (JeromeMartinez) [inline Source/GUI/Qt/App.cpp:48]: We have `setlocale(LC_ALL, "");` just before, doesn't it work by doing the same command again? I am reluctant to force a specific charset.

Comment (g-maxime) [reply Source/GUI/Qt/App.cpp:48]: setlocale(LC_ALL, "") Applies the locale from the environment but when launched from the finder there isn't any.

So the default ANSI-C locale is used.

Comment (JeromeMartinez) [reply Source/GUI/Qt/App.cpp:48]: Would it make sense to test `getlocale(LC_ALL, NULL)` (reading current locale) before forcing UTF-8, in case Apple puts another locale one day?
